### ISSUE TITLE
Fixing the index page

### ISSUE THREAD

**Issue by sahilsingh7735** [sahilsingh7735/web#34] opened 2022-10-30 09:15 UTC
Fix the index page,

**Comment by vedamruta** [comment] 2022-10-30 14:19
Hey, I will try to fix the page. Please assign this issue to me :)

**Comment by vedamruta** [comment] 2022-10-30 14:40
I ain't understanding what you want on the index.html page ?? Because I saw your repo, it already has sevenwonders.html file in which you tried to display seven wonders. Do I need to display Caraousel of 7 wonders' pictures  on the index.html page ??

**Comment by DHRUVKHANDELWAL00** [comment] 2022-10-31 06:26
hey @sahilsingh7735 , please assign it to me.

**Comment by bilalshaikh292** [comment] 2023-08-10 06:45
heyy @sahilsingh7735  is the issue still open I would like to contribute?

**Comment by apoorv654123** [comment] 2023-09-22 18:54
if the issue is open i am trying to **contribute** in it

**Closed as completed** 2023-10-02 07:53 UTC
Labels: good first issue, hacktoberfest, first time only, goodfirstissue, hacktoberfest2020, hacktoberfest-accepted
